-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--    Lex0x00 Arch Linux Setup

--#################################################

--

-- ── NVIDIA ──

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("NVD_BACKEND", "direct")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.env("__NV_PRIME_RENDER_OFFLOAD", 1)

hl.env("__NV_PRIME_RENDER_OFFLOAD_PROVIDER", "NVIDIA-G0")

hl.env("__VK_LAYER_NV_optimus", "NVIDIA_only")

hl.env("AQ_DRM_DEVICES", "/dev/dri/card1:/dev/dri/card0")

-- ── AUTOSTART ──────────────────────────────────










-- ── MONITOR ────────────────────────────────────

-- Ajusta según tu monitor: monitor=name,resolution@hz,position,scale

hl.monitor({
    output   = "DP-1",
    mode     = "1920x1080@165",
    position = "auto",
    scale    = 1,
})

-- ── INPUT ──────────────────────────────────────

hl.config({
    input = {
        kb_layout = "us",
        kb_options = "grp:alt_shift_toggle",
        follow_mouse = 1,
        sensitivity = 0,
        accel_profile = "flat",
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            disable_while_typing = true,
        },
    },
})

-- ── GENERAL ────────────────────────────────────

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 2,
        -- Gruvbox Material Dark palette
        layout = "dwindle",
        resize_on_border = true,
        allow_tearing = false,
        col = {
            active_border = { colors = { "rgb(a9b665)", "rgb(d8a657)" }, angle = 45 },
            inactive_border = "rgb(3c3836)",
        },
    },
})

-- ── DECORATION ─────────────────────────────────

hl.config({
    decoration = {
        rounding = 6,
        blur = {
            enabled = true,
            size = 6,
            passes = 3,
            noise = 0.02,
            contrast = 1.0,
            brightness = 0.85,
        },
        shadow = {
            enabled = true,
            range = 20,
            render_power = 3,
            color = "rgba(1d2021dd)",
            color_inactive = "rgba(1d202188)",
        },
        dim_inactive = true,
        dim_strength = 0.08,
    },
})

-- ── ANIMATIONS ─────────────────────────────────

hl.config({
    animations = {
        enabled = true,
    },
})
hl.curve("ease", {
    type = "bezier",
    points = { { 0.25, 0.1 }, { 0.25, 1.0 } },
})
hl.curve("easeOut", {
    type = "bezier",
    points = { { 0.0, 0.0 }, { 0.2, 1.0 } },
})
hl.curve("easeInOut", {
    type = "bezier",
    points = { { 0.4, 0.0 }, { 0.6, 1.0 } },
})
hl.curve("overshot", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})
hl.curve("spring", {
    type = "bezier",
    points = { { 0.68, -0.55 }, { 0.27, 1.55 } },
})
hl.animation({ leaf = "windows", enabled = true, speed = 2, bezier = "easeOut", style = "popin 85%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.8, bezier = "easeOut", style = "popin 85%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 1.3, bezier = "easeInOut" })
hl.animation({ leaf = "border", enabled = true, speed = 8, bezier = "ease" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 12, bezier = "ease", style = "loop" })
hl.animation({ leaf = "fade", enabled = true, speed = 4, bezier = "easeOut" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.5, bezier = "easeOut", style = "slidefadevert 20%" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3.5, bezier = "easeOut", style = "slidevert" })

-- ── LAYOUTS ────────────────────────────────────

hl.config({
    dwindle = {
        preserve_split = true,
        smart_split = false,
        smart_resizing = true,
    },
})

hl.config({
    master = {
        new_status = "slave",
        new_on_top = false,
        mfact = 0.55,
    },
})

-- ── MISC ───────────────────────────────────────

hl.config({
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        vrr = 0,
        focus_on_activate = true,
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
    },
})

-- ── WINDOW RULES ───────────────────────────────

-- Floating windows

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(org.gnome.Calculator)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(imv)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(mpv)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(file-roller)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Keybinds)$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_800_600",
    match = {
        title = "^(Keybinds)$",
    },
    size = { 800, 600 },
})

hl.window_rule({
    name  = "center_on",
    match = {
        title = "^(Keybinds)$",
    },
    center = true,
})

-- Sizes for floats

hl.window_rule({
    name  = "size_800_500",
    match = {
        class = "^(pavucontrol)$",
    },
    size = { 800, 500 },
})

hl.window_rule({
    name  = "size_900_600",
    match = {
        class = "^(blueman-manager)$",
    },
    size = { 900, 600 },
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "^(pavucontrol)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "^(blueman-manager)$",
    },
    center = true,
})

-- Opacity

--windowrule = match:class ^(Alacritty)$, opacity 0.92 0.85

--windowrule = match:class ^(kitty)$, opacity 0.92 0.85

--windowrule = match:class ^(Code)$, opacity 0.95 0.90

--windowrule = match:class ^(neovide)$, opacity 0.95 0.90

-- Rounding para terminal

hl.window_rule({
    name  = "rounding_4",
    match = {
        class = "^(Alacritty)$",
    },
    rounding = 4,
})

-- Idle inhibit for media

-- Picture-in-picture

hl.window_rule({
    name  = "pin_on",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    pin = true,
})

-- Workspace assignments

hl.window_rule({
    name  = "workspace_2",
    match = {
        class = "^(firefox)$",
    },
    workspace = 2,
})

hl.window_rule({
    name  = "workspace_2",
    match = {
        class = "^(brave-browser)$",
    },
    workspace = 2,
})

hl.window_rule({
    name  = "workspace_3",
    match = {
        class = "^(Code)$",
    },
    workspace = 3,
})

hl.window_rule({
    name  = "workspace_3",
    match = {
        class = "^(neovide)$",
    },
    workspace = 3,
})

hl.window_rule({
    name  = "workspace_4",
    match = {
        class = "^(discord)$",
    },
    workspace = 4,
})

hl.window_rule({
    name  = "workspace_4",
    match = {
        class = "^(WebCord)$",
    },
    workspace = 4,
})

-- ── ENVIRONMENT ────────────────────────────────

hl.env("XCURSOR_SIZE", 24)

hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")

hl.env("GTK_THEME", "Gruvbox-Dark")

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("QT_QPA_PLATFORMTHEME", "gtk2")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("GDK_BACKEND", "wayland,x11")

hl.env("SDL_VIDEODRIVER", "wayland")

hl.env("CLUTTER_BACKEND", "wayland")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("MOZ_ENABLE_WAYLAND", 1)

-- ── VARIABLES ──────────────────────────────────

local mod = "SUPER"

local term = "kitty"

local menu = "wofi --show drun"

local browser = "firefox"

local filemanager = "thunar"

local editor = "code"

-- ── KEYBINDINGS ────────────────────────────────

-- Sistema

hl.bind(mod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))

hl.bind(mod .. " + " .. "D", hl.dsp.exec_cmd("wofi --show drun"))

hl.bind(mod .. " + " .. "B", hl.dsp.exec_cmd("firefox"))

hl.bind(mod .. " + " .. "E", hl.dsp.exec_cmd("thunar"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "Return", hl.dsp.exec_cmd("code"))

-- Hyprland controls

hl.bind(mod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exit())

hl.bind(mod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mod .. " + " .. "Space", hl.dsp.window.float())

hl.bind(mod .. " + " .. "P", hl.dsp.window.pseudo())

hl.bind(mod .. " + " .. "J", hl.dsp.layout("togglesplit"))

hl.bind(mod .. " + " .. "Tab", hl.dsp.window.cycle_next())

-- Screenshots

hl.bind("Print", hl.dsp.exec_cmd("grimblast copy area"))

hl.bind("SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd("grimblast copy output"))

hl.bind(mod .. " + " .. "Print", hl.dsp.exec_cmd("grimblast copysave area ~/Pictures/Screenshots/$(date +%Y%m%d_%H%M%S).png"))

hl.bind("CTRL + ALT" .. " + " .. "S", hl.dsp.exec_cmd("grimblast copysave area ~/Pictures/Screenshots/$(date +%Y%m%d_%H%M%S).png"))

-- Portapapeles

hl.bind(mod .. " + " .. "V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))

-- Bloquear pantalla

hl.bind(mod .. " + " .. "M", hl.dsp.exec_cmd("hyprlock"))

-- Notificaciones

hl.bind(mod .. " + " .. "N", hl.dsp.exec_cmd("dunstctl close-all"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("dunstctl history-pop"))

-- ── FOCO (vim-style) ───────────────────────────

hl.bind(mod .. " + " .. "h", hl.dsp.focus({ direction = "left" }))

hl.bind(mod .. " + " .. "l", hl.dsp.focus({ direction = "right" }))

hl.bind(mod .. " + " .. "k", hl.dsp.focus({ direction = "up" }))

hl.bind(mod .. " + " .. "j", hl.dsp.focus({ direction = "down" }))

-- ── MOVER VENTANAS ─────────────────────────────

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "h", hl.dsp.window.move({ direction = "left" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "l", hl.dsp.window.move({ direction = "right" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "k", hl.dsp.window.move({ direction = "up" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "j", hl.dsp.window.move({ direction = "down" }))

-- ── RESIZE ─────────────────────────────────────

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "h", hl.dsp.window.resize({ x = -40, y = 0, relative = true }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "l", hl.dsp.window.resize({ x = 40, y = 0, relative = true }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "k", hl.dsp.window.resize({ x = 0, y = -40, relative = true }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "j", hl.dsp.window.resize({ x = 0, y = 40, relative = true }))

-- ── WORKSPACES (1–10) ──────────────────────────

hl.bind(mod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Scratchpad

hl.bind(mod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll entre workspaces

hl.bind(mod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- ── MOUSE ──────────────────────────────────────

hl.bind(mod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- ── AUDIO ──────────────────────────────────────

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

-- ── BRILLO ─────────────────────────────────────

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true })

-- ── MEDIA ──────────────────────────────────────

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- ── s ──────────────────────────────────────

hl.bind(mod .. " + " .. "F1", hl.dsp.exec_cmd("~/.config/hypr/scripts/cheatsheet.sh"))

hl.bind(mod .. " + " .. "W", hl.dsp.exec_cmd("~/.config/hypr/scripts/network.sh"))

-- ── AUTOSTART ──



-- ── DEBUG ──────────────────────────────────────

hl.config({
    debug = {
        vfr = true,
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("dunst")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("systemd-run --user hyprpolkitagent")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("pkill -f xwaylandvideobridge")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("swww img /home/javikrd/Pictures/Wallpapers/gruvbox_tux.png --transition-type wipe --transition-angle 30")
end)
